### ISSUE TITLE
Right half pcb not working after flash

### ISSUE THREAD

**Issue by karlmacklin** [janlonden/nyquist-keymap#1]
I never could get the right half functioning after flash.

However, if I commented out these two in config.h:
```
// #define USE_I2C
// #define MASTER_LEFT
```

it works!

**Comment by janlonden** [comment]
Have you tried flashing both sides? That's what I've been doing and I haven't had any issues. I don't think I want to lose the increased speed you get with I2C enabled, even though I don't have any reasons why one would need the increased speed.

**Comment by karlmacklin** [comment]
Haven't tried, didn't know about I2C and what it did. Will probably work! :)
